baseURL = "https://blog-a27bd.firebaseapp.com/"
languageCode = "en-us"
title = "A cloud-native world"
theme = "minimo"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

enableRobotsTXT = true

disqusShortname = ""
googleAnalytics = ""

[params.widgets]
homepage = ["recent_posts"]
sidebar = ["about","sidebar_menu","taxonomy_cloud"]
footer = ["social_menu"]

[params.copyright]
prefix = ""
holder = "laurentgrangeau"
startYear = "2018"
suffix = ""

[params.opengraph.twitter]
page = "laurentgrangeau" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
email = "laurent.grangeau@gmail.com"
github = "laurentgrangeau"
linkedin = "laurentgrangeau"
twitter = "laurentgrangeau"

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
showReadingTime = true
showLastmod = true
taxonomyCloudShuffle = true
accentColor = "#ffcd00"
hideMainMenu = false

[params.sidebar]
enable = true

[params.info]
description = "A blog about serverless, containers and more"
title404 = "Nothing's here!"

[params.comments]
enable = false

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"